### ISSUE TITLE
(Now that ```d->child_list.at(i)``` is repeated, there's a case for saving it in a local variable to save duplication.)

### ISSUE THREAD

**Issue by Shahinbagerzadsaid977** [Shahinbagerzadsaid977/skills-introduction-to-github#2]
(Now that ```d->child_list.at(i)``` is repeated, there's a case for saving it in a local variable to save duplication.)

Why do the deletion after redoing (or, below, undoing) if the operation is obsolete ?  Surely, if it makes no difference, it can simply be removed without {un,re}doing.

For that matter, why even delete it ?

_Originally posted by @ediosyncratic in https://github.com/qt/qtbase/pull/109#discussion_r1869214515_

**Comment by ediosyncratic** [comment]
The reason for leaving it until after is that the act of redoing or undoing may discover its redundancy; however, the redoing or undoing could be conditioned on not being already redundant, as is done in the other code doing similar.
As for why even delete it, I guess that's about tidiness and matching the other class that does similar; see earlier discussion.
